{
  "_id": "_design/export",
  "lists": {
    "text": "function(head,req) { var row; start({ 'headers': { 'Content-Type': 'text/plain' } }); while(row = getRow()) { send(row.value); } }"
  },
  "views": {
    "ris": {
      "map": "function(doc) {\n  if (!doc.citebank || doc.citebank.type != 'work' || doc.citebank.deleted) {\n    return;\n  }\n\n  var ris = [];\n\n  var genre = '';\n\n  switch (doc.type) {\n    case \"article-journal\":\n      genre = 'JOUR';\n      break;\n    case \"chapter\":\n      genre = 'CHAP';\n      break;\n    case \"boo\":\n      genre = 'BOOK';\n      break;\n    default:\n      genre = 'GEN';\n      break;\n  }\n\n  ris.push('TY  - ' + genre);\n\n  ris.push('ID  - ' + doc._id);\n\n  for (var i in doc) {\n    switch (i) {\n\n      case 'title':\n        var title = '';\n        if (Array.isArray(doc[i])) {\n          title = doc[i][0];\n        }\n        else {\n          title = doc[i];\n        }\n        ris.push('TI  - ' + title);\n        break;\n\n      case 'author':\n        for (var j in doc[i]) {\n          if (doc[i][j].family && doc[i][j].given) {\n            ris.push('AU  - ' + doc[i][j].family + ', ' + doc[i][j].given);\n          }\n          else {\n            ris.push('AU  - ' + doc[i][j].literal);\n          }\n        }\n        break;\n\n      case 'container-title':\n        var container = '';\n        if (Array.isArray(doc[i])) {\n          container = doc[i][0];\n        }\n        else {\n          container = doc[i];\n        }\n        // need to handle this differently for different types\n        ris.push('JO  - ' + container);\n        break;\n\n      case 'volume':\n        ris.push('VL  - ' + doc[i]);\n        break;\n\n      case 'issue':\n        ris.push('IS  - ' + doc[i]);\n        break;\n\n      case 'page':\n        var m = doc[i].match(/(\\d+)[-|–|−](\\d+)/);\n        if (m) {\n          ris.push('SP  - ' + parseInt(m[1]));\n          ris.push('EP  - ' + parseInt(m[2]));\n        }\n        else {\n          ris.push('SP  - ' + parseInt(doc[i]));\n        }\n        break;\n\n      case 'issued':\n        ris.push('Y1  - ' + doc[i]['date-parts'][0][0]);\n        break;\n\n      case 'DOI':\n        ris.push('DO  - ' + doc[i]);\n        break;\n\n      case 'URL':\n        if (Array.isArray(doc[i])) {\n          for (j in doc[i]) {\n            ris.push('UR  - ' + doc[i][j]);\n          }\n        }\n        else {\n          ris.push('UR  - ' + doc[i]);\n        }\n        break;\n\n      default:\n        break;\n    }\n  }\n  ris.push(\"ER  - \\n\\n\");\n  emit(doc._id, ris.join(\"\\n\"));\n}"
    }
  },
  "language": "javascript"
}